ALTER TABLE armi.schema_baseline_identity DROP CONSTRAINT schema_baseline_identity_value_check;
ALTER TABLE armi.schema_baseline_identity ADD CONSTRAINT schema_baseline_identity_value_check CHECK (baseline_identity = 'armi.schema-baseline.v18'::text) NOT VALID;
UPDATE armi.schema_baseline_identity SET baseline_identity = 'armi.schema-baseline.v18';
ALTER TABLE armi.schema_baseline_identity VALIDATE CONSTRAINT schema_baseline_identity_value_check;

ALTER TABLE armi.cognitive_candidate_validations ADD COLUMN diagnostic_artifact_id uuid;
ALTER TABLE armi.cognitive_candidate_validations ADD CONSTRAINT cognitive_candidate_validations_diagnostic_artifact_id_fkey FOREIGN KEY (diagnostic_artifact_id) REFERENCES armi.artifacts(artifact_id);

ALTER TABLE armi.cognitive_attempts DROP CONSTRAINT cognitive_attempts_candidate_schema_version_check;
ALTER TABLE armi.cognitive_attempts ADD CONSTRAINT cognitive_attempts_candidate_schema_version_check CHECK ((candidate_schema_version = ANY (ARRAY['armi.cognition-candidate.v12'::text, 'armi.creator-dialogue-candidate.v25'::text, 'armi.creator-cognitive-act-candidate.v3'::text, 'armi.creator-voice-act-candidate.v3'::text, 'armi.autonomous-activity-candidate.v4'::text, 'armi.activity-attention-candidate.v4'::text, 'armi.activity-internal-work-candidate.v3'::text, 'armi.sleep-decision-candidate.v1'::text, 'armi.maintenance-work-candidate.v1'::text, 'armi.owner-reflection-candidate.v1'::text, 'armi.other-human-dialogue-candidate.v6'::text, 'armi.visual-observation-candidate.v1'::text, 'armi.creator-cognitive-act-candidate.v4'::text, 'armi.creator-voice-act-candidate.v4'::text, 'armi.cognition-candidate.v13'::text, 'armi.activity-attention-candidate.v5'::text, 'armi.activity-internal-work-candidate.v4'::text, 'armi.autonomous-activity-candidate.v5'::text, 'armi.other-human-dialogue-candidate.v7'::text, 'armi.visual-observation-candidate.v2'::text, 'armi.owner-reflection-candidate.v2'::text, 'armi.maintenance-work-candidate.v2'::text])));
ALTER TABLE armi.cognitive_candidate_validations DROP CONSTRAINT cognitive_candidate_validation_candidate_contract_version_check;
ALTER TABLE armi.cognitive_candidate_validations ADD CONSTRAINT cognitive_candidate_validation_candidate_contract_version_check CHECK ((candidate_contract_version = ANY (ARRAY['armi.cognition-candidate.v12'::text, 'armi.creator-dialogue-candidate.v25'::text, 'armi.creator-cognitive-act-candidate.v3'::text, 'armi.creator-voice-act-candidate.v3'::text, 'armi.autonomous-activity-candidate.v4'::text, 'armi.activity-attention-candidate.v4'::text, 'armi.activity-internal-work-candidate.v3'::text, 'armi.sleep-decision-candidate.v1'::text, 'armi.maintenance-work-candidate.v1'::text, 'armi.owner-reflection-candidate.v1'::text, 'armi.other-human-dialogue-candidate.v6'::text, 'armi.visual-observation-candidate.v1'::text, 'armi.creator-cognitive-act-candidate.v4'::text, 'armi.creator-voice-act-candidate.v4'::text, 'armi.cognition-candidate.v13'::text, 'armi.activity-attention-candidate.v5'::text, 'armi.activity-internal-work-candidate.v4'::text, 'armi.autonomous-activity-candidate.v5'::text, 'armi.other-human-dialogue-candidate.v7'::text, 'armi.visual-observation-candidate.v2'::text, 'armi.owner-reflection-candidate.v2'::text, 'armi.maintenance-work-candidate.v2'::text])));
