-- Preserve historical appraisals and append current Owner formats without reinterpreting history.
ALTER TABLE armi.cognitive_attempts DROP CONSTRAINT cognitive_attempts_candidate_schema_version_check;
ALTER TABLE armi.cognitive_attempts ADD CONSTRAINT cognitive_attempts_candidate_schema_version_check CHECK ((candidate_schema_version = ANY (ARRAY['armi.cognition-candidate.v12'::text, 'armi.creator-dialogue-candidate.v25'::text, 'armi.creator-dialogue-candidate.v26'::text, 'armi.creator-cognitive-act-candidate.v3'::text, 'armi.creator-voice-act-candidate.v3'::text, 'armi.autonomous-activity-candidate.v4'::text, 'armi.activity-attention-candidate.v4'::text, 'armi.activity-internal-work-candidate.v3'::text, 'armi.sleep-decision-candidate.v1'::text, 'armi.maintenance-work-candidate.v1'::text, 'armi.owner-reflection-candidate.v1'::text, 'armi.other-human-dialogue-candidate.v6'::text, 'armi.visual-observation-candidate.v1'::text, 'armi.creator-cognitive-act-candidate.v4'::text, 'armi.creator-cognitive-act-candidate.v5'::text, 'armi.creator-cognitive-act-candidate.v6'::text, 'armi.creator-voice-act-candidate.v4'::text, 'armi.creator-voice-act-candidate.v5'::text, 'armi.creator-voice-act-candidate.v6'::text, 'armi.cognition-candidate.v13'::text, 'armi.cognition-candidate.v14'::text, 'armi.cognition-candidate.v15'::text, 'armi.cognition-candidate.v16'::text, 'armi.activity-attention-candidate.v5'::text, 'armi.activity-internal-work-candidate.v4'::text, 'armi.activity-internal-work-candidate.v5'::text, 'armi.autonomous-activity-candidate.v5'::text, 'armi.autonomous-activity-candidate.v6'::text, 'armi.autonomous-activity-candidate.v7'::text, 'armi.autonomous-activity-candidate.v8'::text, 'armi.autonomous-activity-candidate.v9'::text, 'armi.autonomous-activity-candidate.v10'::text, 'armi.other-human-dialogue-candidate.v7'::text, 'armi.other-human-dialogue-candidate.v8'::text, 'armi.other-human-dialogue-candidate.v9'::text, 'armi.visual-observation-candidate.v2'::text, 'armi.visual-observation-candidate.v3'::text, 'armi.visual-observation-candidate.v4'::text, 'armi.owner-reflection-candidate.v2'::text, 'armi.owner-reflection-candidate.v3'::text, 'armi.owner-reflection-candidate.v4'::text, 'armi.maintenance-work-candidate.v2'::text, 'armi.maintenance-work-candidate.v3'::text])));
ALTER TABLE armi.cognitive_candidate_validations DROP CONSTRAINT cognitive_candidate_validation_candidate_contract_version_check;
ALTER TABLE armi.cognitive_candidate_validations ADD CONSTRAINT cognitive_candidate_validation_candidate_contract_version_check CHECK ((candidate_contract_version = ANY (ARRAY['armi.cognition-candidate.v12'::text, 'armi.creator-dialogue-candidate.v25'::text, 'armi.creator-dialogue-candidate.v26'::text, 'armi.creator-cognitive-act-candidate.v3'::text, 'armi.creator-voice-act-candidate.v3'::text, 'armi.autonomous-activity-candidate.v4'::text, 'armi.activity-attention-candidate.v4'::text, 'armi.activity-internal-work-candidate.v3'::text, 'armi.sleep-decision-candidate.v1'::text, 'armi.maintenance-work-candidate.v1'::text, 'armi.owner-reflection-candidate.v1'::text, 'armi.other-human-dialogue-candidate.v6'::text, 'armi.visual-observation-candidate.v1'::text, 'armi.creator-cognitive-act-candidate.v4'::text, 'armi.creator-cognitive-act-candidate.v5'::text, 'armi.creator-cognitive-act-candidate.v6'::text, 'armi.creator-voice-act-candidate.v4'::text, 'armi.creator-voice-act-candidate.v5'::text, 'armi.creator-voice-act-candidate.v6'::text, 'armi.cognition-candidate.v13'::text, 'armi.cognition-candidate.v14'::text, 'armi.cognition-candidate.v15'::text, 'armi.cognition-candidate.v16'::text, 'armi.activity-attention-candidate.v5'::text, 'armi.activity-internal-work-candidate.v4'::text, 'armi.activity-internal-work-candidate.v5'::text, 'armi.autonomous-activity-candidate.v5'::text, 'armi.autonomous-activity-candidate.v6'::text, 'armi.autonomous-activity-candidate.v7'::text, 'armi.autonomous-activity-candidate.v8'::text, 'armi.autonomous-activity-candidate.v9'::text, 'armi.autonomous-activity-candidate.v10'::text, 'armi.other-human-dialogue-candidate.v7'::text, 'armi.other-human-dialogue-candidate.v8'::text, 'armi.other-human-dialogue-candidate.v9'::text, 'armi.visual-observation-candidate.v2'::text, 'armi.visual-observation-candidate.v3'::text, 'armi.visual-observation-candidate.v4'::text, 'armi.owner-reflection-candidate.v2'::text, 'armi.owner-reflection-candidate.v3'::text, 'armi.owner-reflection-candidate.v4'::text, 'armi.maintenance-work-candidate.v2'::text, 'armi.maintenance-work-candidate.v3'::text])));
ALTER TABLE armi.mood_appraisal_events DROP CONSTRAINT mood_appraisal_events_derivation_version_check;
ALTER TABLE armi.mood_appraisal_events ADD CONSTRAINT mood_appraisal_events_derivation_version_check CHECK ((derivation_version IN ('cpm-fuzzy.v2'::text, 'cpm-fuzzy.v3'::text)));
ALTER TABLE armi.mood_appraisal_events DROP CONSTRAINT mood_appraisal_events_semantic_version_check;
ALTER TABLE armi.mood_appraisal_events ADD CONSTRAINT mood_appraisal_events_semantic_version_check CHECK ((((data_rights_redacted_at IS NOT NULL) OR ((appraisal_payload ->> 'schema_version'::text) = 'armi.mood-appraisal.v2'::text AND appraisal_mapping_version = 'semantic-anchors.v1'::text AND (derived_appraisal_payload ->> 'schema_version'::text) = 'armi.mood-derived-appraisal.v2'::text AND derivation_version = 'cpm-fuzzy.v2'::text))) OR (((data_rights_redacted_at IS NOT NULL) OR ((appraisal_payload ->> 'schema_version'::text) = 'armi.mood-appraisal.v3'::text AND appraisal_mapping_version = 'semantic-anchors.v1'::text AND (derived_appraisal_payload ->> 'schema_version'::text) = 'armi.mood-derived-appraisal.v3'::text AND derivation_version = 'cpm-fuzzy.v3'::text))));
ALTER TABLE armi.mood_revisions DROP CONSTRAINT mood_revisions_payload_check;
ALTER TABLE armi.mood_revisions ADD CONSTRAINT mood_revisions_payload_check CHECK ((((semantic_payload ->> 'schema_version'::text) = 'armi.mood.v3'::text AND (semantic_payload ?& ARRAY['dynamics_version'::text, 'derivation_version'::text, 'home_base'::text, 'schema_version'::text]) AND (semantic_payload - ARRAY['dynamics_version'::text, 'derivation_version'::text, 'home_base'::text, 'schema_version'::text]) = '{}'::jsonb AND (semantic_payload ->> 'dynamics_version'::text) = 'recency-reappraisal.v1'::text AND (semantic_payload ->> 'derivation_version'::text) = 'cpm-fuzzy.v2'::text AND jsonb_typeof(semantic_payload -> 'home_base'::text) = 'object'::text AND (semantic_payload -> 'home_base'::text) ?& ARRAY['valence'::text, 'arousal'::text, 'dominance'::text] AND ((semantic_payload -> 'home_base'::text) - ARRAY['valence'::text, 'arousal'::text, 'dominance'::text]) = '{}'::jsonb AND (((semantic_payload -> 'home_base'::text) ->> 'valence'::text)::integer BETWEEN -100 AND 100) AND (((semantic_payload -> 'home_base'::text) ->> 'arousal'::text)::integer BETWEEN -100 AND 100) AND (((semantic_payload -> 'home_base'::text) ->> 'dominance'::text)::integer BETWEEN -100 AND 100))) OR (((semantic_payload ->> 'schema_version'::text) = 'armi.mood.v4'::text AND (semantic_payload ?& ARRAY['dynamics_version'::text, 'derivation_version'::text, 'home_base'::text, 'schema_version'::text]) AND (semantic_payload - ARRAY['dynamics_version'::text, 'derivation_version'::text, 'home_base'::text, 'schema_version'::text]) = '{}'::jsonb AND (semantic_payload ->> 'dynamics_version'::text) = 'recency-reappraisal.v1'::text AND (semantic_payload ->> 'derivation_version'::text) = 'cpm-fuzzy.v3'::text AND jsonb_typeof(semantic_payload -> 'home_base'::text) = 'object'::text AND (semantic_payload -> 'home_base'::text) ?& ARRAY['valence'::text, 'arousal'::text, 'dominance'::text] AND ((semantic_payload -> 'home_base'::text) - ARRAY['valence'::text, 'arousal'::text, 'dominance'::text]) = '{}'::jsonb AND (((semantic_payload -> 'home_base'::text) ->> 'valence'::text)::integer BETWEEN -100 AND 100) AND (((semantic_payload -> 'home_base'::text) ->> 'arousal'::text)::integer BETWEEN -100 AND 100) AND (((semantic_payload -> 'home_base'::text) ->> 'dominance'::text)::integer BETWEEN -100 AND 100))));
DO $migration$
DECLARE head record; new_revision uuid;
BEGIN
  FOR head IN SELECT r.* FROM armi.mind_heads h JOIN armi.mind_revisions r ON r.mind_revision_id=h.current_revision_id
  LOOP
    IF head.semantic_payload->>'schema_version' <> 'armi.mind.v3' THEN RAISE EXCEPTION 'DB-UPGRADE-MIND-FORMAT'; END IF;
    new_revision=uuidv7();
    INSERT INTO armi.mind_revisions(mind_revision_id,subject_id,mind_version,previous_revision_id,origin_kind,origin_ref,semantic_payload,privacy_scope)
    VALUES(new_revision,head.subject_id,head.mind_version+1,head.mind_revision_id,'module_migration',new_revision,head.semantic_payload || '{"schema_version":"armi.mind.v4","motivation_states":[]}'::jsonb,'private');
    UPDATE armi.mind_heads SET current_revision_id=new_revision,mind_version=head.mind_version+1 WHERE subject_id=head.subject_id;
  END LOOP;
  FOR head IN SELECT r.* FROM armi.mood_heads h JOIN armi.mood_revisions r ON r.mood_revision_id=h.current_revision_id
  LOOP
    IF head.semantic_payload->>'schema_version' <> 'armi.mood.v3' THEN RAISE EXCEPTION 'DB-UPGRADE-MOOD-FORMAT'; END IF;
    new_revision=uuidv7();
    INSERT INTO armi.mood_revisions(mood_revision_id,subject_id,mood_version,previous_revision_id,origin_kind,origin_ref,semantic_payload,privacy_scope)
    VALUES(new_revision,head.subject_id,head.mood_version+1,head.mood_revision_id,'module_migration',new_revision,head.semantic_payload || '{"schema_version":"armi.mood.v4","derivation_version":"cpm-fuzzy.v3"}'::jsonb,'private');
    UPDATE armi.mood_heads SET current_revision_id=new_revision,mood_version=head.mood_version+1 WHERE subject_id=head.subject_id;
  END LOOP;
END $migration$;
ALTER TABLE armi.schema_baseline_identity DROP CONSTRAINT schema_baseline_identity_value_check;
UPDATE armi.schema_baseline_identity SET baseline_identity='armi.schema-baseline.v26';
ALTER TABLE armi.schema_baseline_identity ADD CONSTRAINT schema_baseline_identity_value_check CHECK (baseline_identity='armi.schema-baseline.v26');
