-- Keep the recorded task and delivered result; retire file-validation machinery.
ALTER TABLE armi.codex_verification_results DROP CONSTRAINT codex_verification_results_check;
UPDATE armi.codex_verification_results AS result
SET final_result_artifact_id=COALESCE(
    result.final_result_artifact_id,
    (SELECT source.evidence_artifact_id FROM armi.codex_result_sources AS source
     WHERE source.codex_verification_id=result.codex_verification_id),
    result.validation_report_artifact_id)
WHERE result.final_result_artifact_id IS NULL;
ALTER TABLE armi.codex_verification_results
    ALTER COLUMN final_result_artifact_id SET NOT NULL,
    DROP COLUMN source_tree_digest,
    DROP COLUMN final_tree_digest,
    DROP COLUMN patch_digest,
    DROP COLUMN event_transcript_artifact_id,
    DROP COLUMN patch_artifact_id,
    DROP COLUMN result_bundle_artifact_id,
    DROP COLUMN diagnostics_artifact_id,
    DROP COLUMN validation_report_artifact_id,
    DROP COLUMN changed_path_count,
    ADD CONSTRAINT codex_verification_results_check CHECK ((execution_status <> 'verified'::text OR execution_error_code IS NULL));
ALTER TABLE armi.codex_task_sources
    DROP COLUMN source_bundle_artifact_id,
    DROP COLUMN source_bundle_digest,
    DROP COLUMN source_tree_digest,
    DROP COLUMN validator_id;
ALTER TABLE armi.action_intent_revisions DROP CONSTRAINT action_intent_revisions_family_check;
ALTER TABLE armi.action_intent_revisions DROP COLUMN validator_id;
ALTER TABLE armi.schema_baseline_identity DROP CONSTRAINT schema_baseline_identity_value_check;
UPDATE armi.schema_baseline_identity SET baseline_identity='armi.schema-baseline.v27';
ALTER TABLE armi.schema_baseline_identity ADD CONSTRAINT schema_baseline_identity_value_check CHECK (baseline_identity='armi.schema-baseline.v27');
ALTER TABLE armi.action_intent_revisions ADD CONSTRAINT action_intent_revisions_family_check CHECK ((((response_artifact_id IS NOT NULL) AND (response_digest IS NOT NULL) AND (response_bytes IS NOT NULL) AND (media_type IS NOT NULL) AND (capability_kind = 'creator.scene.reply'::text) AND (operation_class = 'send'::text) AND (audience_scope = 'creator'::text) AND (data_scope = 'creator_visible_response'::text) AND (purpose = 'respond_to_creator'::text) AND (codex_task_source_id IS NULL) AND (task_manifest_digest IS NULL)) OR ((response_artifact_id IS NOT NULL) AND (response_digest IS NOT NULL) AND (response_bytes IS NOT NULL) AND (media_type IS NOT NULL) AND (capability_kind = 'local.other-human-inbox.deliver'::text) AND (operation_class = 'send'::text) AND (audience_scope = 'other_human'::text) AND (data_scope = 'declared_party_response'::text) AND (purpose = 'respond_to_other_human'::text) AND (codex_task_source_id IS NULL) AND (task_manifest_digest IS NULL)) OR ((response_artifact_id IS NOT NULL) AND (response_digest IS NOT NULL) AND (response_bytes IS NOT NULL) AND (media_type IS NOT NULL) AND (capability_kind = 'external.group.message.send'::text) AND (operation_class = 'send'::text) AND (audience_scope = 'social_group'::text) AND (data_scope = 'declared_party_response'::text) AND (purpose = 'respond_to_other_human'::text) AND (codex_task_source_id IS NULL) AND (task_manifest_digest IS NULL)) OR ((response_artifact_id IS NOT NULL) AND (response_digest IS NOT NULL) AND (response_bytes IS NOT NULL) AND (media_type IS NOT NULL) AND (capability_kind = 'external.private.message.send'::text) AND (operation_class = 'send'::text) AND (audience_scope = 'other_human'::text) AND (data_scope = 'declared_party_response'::text) AND (purpose = 'respond_to_other_human'::text) AND (codex_task_source_id IS NULL) AND (task_manifest_digest IS NULL)) OR ((response_artifact_id IS NULL) AND (response_digest IS NULL) AND (response_bytes IS NULL) AND (media_type IS NULL) AND (capability_kind = 'codex.delegated-work'::text) AND (operation_class = 'execute'::text) AND (audience_scope IS NULL) AND (data_scope IS NULL) AND (purpose = 'delegate_codex_work'::text) AND (codex_task_source_id IS NOT NULL) AND (task_manifest_digest IS NOT NULL) AND (task_manifest_digest ~ '^sha256:[0-9a-f]{64}$'::text))));
ALTER TABLE armi.cognitive_attempts DROP CONSTRAINT cognitive_attempts_candidate_schema_version_check;
ALTER TABLE armi.cognitive_attempts ADD CONSTRAINT cognitive_attempts_candidate_schema_version_check CHECK ((candidate_schema_version = ANY (ARRAY['armi.cognition-candidate.v12'::text, 'armi.creator-dialogue-candidate.v25'::text, 'armi.creator-dialogue-candidate.v26'::text, 'armi.creator-cognitive-act-candidate.v3'::text, 'armi.creator-voice-act-candidate.v3'::text, 'armi.autonomous-activity-candidate.v4'::text, 'armi.activity-attention-candidate.v4'::text, 'armi.activity-internal-work-candidate.v3'::text, 'armi.sleep-decision-candidate.v1'::text, 'armi.maintenance-work-candidate.v1'::text, 'armi.owner-reflection-candidate.v1'::text, 'armi.other-human-dialogue-candidate.v6'::text, 'armi.visual-observation-candidate.v1'::text, 'armi.creator-cognitive-act-candidate.v4'::text, 'armi.creator-cognitive-act-candidate.v5'::text, 'armi.creator-cognitive-act-candidate.v6'::text, 'armi.creator-voice-act-candidate.v4'::text, 'armi.creator-voice-act-candidate.v5'::text, 'armi.creator-voice-act-candidate.v6'::text, 'armi.cognition-candidate.v13'::text, 'armi.cognition-candidate.v14'::text, 'armi.cognition-candidate.v15'::text, 'armi.cognition-candidate.v16'::text, 'armi.cognition-candidate.v17'::text, 'armi.activity-attention-candidate.v5'::text, 'armi.activity-internal-work-candidate.v4'::text, 'armi.activity-internal-work-candidate.v5'::text, 'armi.autonomous-activity-candidate.v5'::text, 'armi.autonomous-activity-candidate.v6'::text, 'armi.autonomous-activity-candidate.v7'::text, 'armi.autonomous-activity-candidate.v8'::text, 'armi.autonomous-activity-candidate.v9'::text, 'armi.autonomous-activity-candidate.v10'::text, 'armi.other-human-dialogue-candidate.v7'::text, 'armi.other-human-dialogue-candidate.v8'::text, 'armi.other-human-dialogue-candidate.v9'::text, 'armi.visual-observation-candidate.v2'::text, 'armi.visual-observation-candidate.v3'::text, 'armi.visual-observation-candidate.v4'::text, 'armi.owner-reflection-candidate.v2'::text, 'armi.owner-reflection-candidate.v3'::text, 'armi.owner-reflection-candidate.v4'::text, 'armi.maintenance-work-candidate.v2'::text, 'armi.maintenance-work-candidate.v3'::text])));
ALTER TABLE armi.cognitive_candidate_validations DROP CONSTRAINT cognitive_candidate_validation_candidate_contract_version_check;
ALTER TABLE armi.cognitive_candidate_validations ADD CONSTRAINT cognitive_candidate_validation_candidate_contract_version_check CHECK ((candidate_contract_version = ANY (ARRAY['armi.cognition-candidate.v12'::text, 'armi.creator-dialogue-candidate.v25'::text, 'armi.creator-dialogue-candidate.v26'::text, 'armi.creator-cognitive-act-candidate.v3'::text, 'armi.creator-voice-act-candidate.v3'::text, 'armi.autonomous-activity-candidate.v4'::text, 'armi.activity-attention-candidate.v4'::text, 'armi.activity-internal-work-candidate.v3'::text, 'armi.sleep-decision-candidate.v1'::text, 'armi.maintenance-work-candidate.v1'::text, 'armi.owner-reflection-candidate.v1'::text, 'armi.other-human-dialogue-candidate.v6'::text, 'armi.visual-observation-candidate.v1'::text, 'armi.creator-cognitive-act-candidate.v4'::text, 'armi.creator-cognitive-act-candidate.v5'::text, 'armi.creator-cognitive-act-candidate.v6'::text, 'armi.creator-voice-act-candidate.v4'::text, 'armi.creator-voice-act-candidate.v5'::text, 'armi.creator-voice-act-candidate.v6'::text, 'armi.cognition-candidate.v13'::text, 'armi.cognition-candidate.v14'::text, 'armi.cognition-candidate.v15'::text, 'armi.cognition-candidate.v16'::text, 'armi.cognition-candidate.v17'::text, 'armi.activity-attention-candidate.v5'::text, 'armi.activity-internal-work-candidate.v4'::text, 'armi.activity-internal-work-candidate.v5'::text, 'armi.autonomous-activity-candidate.v5'::text, 'armi.autonomous-activity-candidate.v6'::text, 'armi.autonomous-activity-candidate.v7'::text, 'armi.autonomous-activity-candidate.v8'::text, 'armi.autonomous-activity-candidate.v9'::text, 'armi.autonomous-activity-candidate.v10'::text, 'armi.other-human-dialogue-candidate.v7'::text, 'armi.other-human-dialogue-candidate.v8'::text, 'armi.other-human-dialogue-candidate.v9'::text, 'armi.visual-observation-candidate.v2'::text, 'armi.visual-observation-candidate.v3'::text, 'armi.visual-observation-candidate.v4'::text, 'armi.owner-reflection-candidate.v2'::text, 'armi.owner-reflection-candidate.v3'::text, 'armi.owner-reflection-candidate.v4'::text, 'armi.maintenance-work-candidate.v2'::text, 'armi.maintenance-work-candidate.v3'::text])));
