[project]
name = "armi-app"
version = "0.0.0"
requires-python = ">=3.14,<3.15"
dependencies = ["armi-admin==0.0.0", "armi-runtime==0.0.0"]

[tool.uv.sources]
armi-admin = { workspace = true }
armi-runtime = { workspace = true }

[build-system]
requires = ["uv_build>=0.11.33,<0.12"]
build-backend = "uv_build"
