"""Generate the fixed A8 kaomoji assets embedded by the mood display firmware."""

# ruff: noqa: RUF001 -- the confusable Unicode characters are the kaomoji data.

from __future__ import annotations

import argparse
import hashlib
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

EXPECTED_FONT_SHA256 = (
    "763146584cf0710223441356b4395e279021b0806c196614377a7a0174ae074a"
)
MAX_WIDTH = 720
MAX_HEIGHT = 160
MAX_FONT_SIZE = 104
MIN_FONT_SIZE = 48
PADDING = 8


@dataclass(frozen=True)
class Face:
    enum_name: str
    label: str
    expression: str


FACES = (
    Face("JOY", "喜悦", "ヽ(>∀<☆)ノ"),
    Face("CONTENTMENT", "满足", "(￣▽￣)~*"),
    Face("INTEREST", "兴趣", "(☆▽☆)"),
    Face("HOPE", "希望", "ヾ(≧▽≦*)o"),
    Face("RELIEF", "如释重负", "(´▽`)ﾉ"),
    Face("AFFECTION", "喜爱", "(⊃≧▽≦)⊃♡"),
    Face("GRATITUDE", "感激", "☆*:.o(≧▽≦)o.:*☆"),
    Face("PRIDE", "自豪", "(￣︶￣)↗"),
    Face("SURPRISE", "惊讶", "Σ(°△°|||)︴"),
    Face("SADNESS", "悲伤", "(╥﹏╥)"),
    Face("FEAR", "恐惧", "Σ(っ °Д °;)っ"),
    Face("ANXIETY", "焦虑", "(⊙﹏⊙;)"),
    Face("ANGER", "愤怒", "(╬▔皿▔)╯"),
    Face("FRUSTRATION", "挫败", "(ノ｀Д´)ノ彡┻━┻"),
    Face("DISGUST", "厌恶", "(￢_￢;)"),
    Face("SHAME", "羞耻", "(*／ω＼*)"),
    Face("GUILT", "内疚", "(´；ω；`)"),
    Face("JEALOUSY", "嫉妒", "(￢ω￢)"),
    Face("BOREDOM", "无聊", "(－_－) zzZ"),
    Face("CONFUSION", "困惑", "(´･ω･`)?"),
    Face("NEUTRAL", "中性", "(・_・)"),
    Face("OFFLINE", "离线", "(－ω－) ..."),
)


def _font(path: Path, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(path, size)


def _supports(font: ImageFont.FreeTypeFont, expression: str) -> bool:
    missing = font.getmask("\u0378", mode="L")
    missing_signature = (missing.size, bytes(missing))
    return all(
        character.isspace()
        or (lambda mask: (mask.size, bytes(mask)) != missing_signature)(
            font.getmask(character, mode="L")
        )
        for character in expression
    )


def _render(path: Path, expression: str) -> tuple[Image.Image, int]:
    for size in range(MAX_FONT_SIZE, MIN_FONT_SIZE - 1, -2):
        font = _font(path, size)
        if not _supports(font, expression):
            if size == MAX_FONT_SIZE:
                missing = [
                    character
                    for character in expression
                    if not character.isspace() and not _supports(font, character)
                ]
                raise ValueError(
                    f"expression contains unsupported glyphs {missing}: {expression}"
                )
            continue
        left, top, right, bottom = font.getbbox(expression)
        width = right - left + 2 * PADDING
        height = bottom - top + 2 * PADDING
        if width <= MAX_WIDTH and height <= MAX_HEIGHT:
            image = Image.new("L", (width, height), 0)
            ImageDraw.Draw(image).text(
                (PADDING - left, PADDING - top), expression, font=font, fill=255
            )
            return image, size
    raise ValueError(f"expression does not fit: {expression}")


def generate(
    font_path: Path,
    output_dir: Path,
    preview_path: Path | None,
) -> None:
    digest = hashlib.sha256(font_path.read_bytes()).hexdigest()
    if digest != EXPECTED_FONT_SHA256:
        raise ValueError(f"unexpected Noto Sans SC source font digest: {digest}")

    rendered = [(face, *_render(font_path, face.expression)) for face in FACES]
    binary = bytearray()
    catalog_lines = [
        "/* Generated by tools/generate_kaomoji_assets.py; do not edit. */",
    ]
    for face, image, size in rendered:
        offset = len(binary)
        binary.extend(image.tobytes())
        escaped = face.expression.replace("\\", "\\\\").replace('"', '\\"')
        catalog_lines.append(
            f'{{"{escaped}", {offset}U, {image.width}U, {image.height}U}}, '
            f"/* {face.enum_name}, {face.label}, {size}px */"
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "mood_text_assets.bin").write_bytes(binary)
    (output_dir / "mood_text_catalog.inc").write_text(
        "\n".join(catalog_lines) + "\n", encoding="utf-8", newline="\n"
    )

    if preview_path is not None:
        sheet = Image.new("RGB", (1600, 2200), "black")
        draw = ImageDraw.Draw(sheet)
        for index, (face, image, size) in enumerate(rendered):
            column = index % 2
            row = index // 2
            x = column * 800
            y = row * 200
            colorized = Image.new("RGB", image.size, "#E6E8EE")
            sheet.paste(colorized, (x + (800 - image.width) // 2, y + 35), image)
            draw.text(
                (x + 12, y + 8),
                f"{face.enum_name} · {size}px",
                fill="#89909E",
            )
        preview_path.parent.mkdir(parents=True, exist_ok=True)
        sheet.save(preview_path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument(
        "--output-dir", type=Path, default=Path(__file__).parents[1] / "main"
    )
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    generate(args.font, args.output_dir, args.preview)


if __name__ == "__main__":
    main()
